# Generated by Django 2.2.3 on 2020-08-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='all_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.All_Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='all_post',
            name='School',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.School'),
        ),
        migrations.AddField(
            model_name='all_post',
            name='all_community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='community.All_Community'),
        ),
        migrations.AddField(
            model_name='all_post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='all_like_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='all_post',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
